//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.dc3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.dc3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Clack_1 {
            get {
                return ResourceManager.GetStream("Clack_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Clack_2 {
            get {
                return ResourceManager.GetStream("Clack_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Clack_3 {
            get {
                return ResourceManager.GetStream("Clack_3", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Clack_4 {
            get {
                return ResourceManager.GetStream("Clack_4", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Clack_5 {
            get {
                return ResourceManager.GetStream("Clack_5", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Clack_6 {
            get {
                return ResourceManager.GetStream("Clack_6", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Clack_7 {
            get {
                return ResourceManager.GetStream("Clack_7", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Click_1 {
            get {
                return ResourceManager.GetStream("Click_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Click_2 {
            get {
                return ResourceManager.GetStream("Click_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Click_3 {
            get {
                return ResourceManager.GetStream("Click_3", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Click_4 {
            get {
                return ResourceManager.GetStream("Click_4", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Click_5 {
            get {
                return ResourceManager.GetStream("Click_5", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Click_6 {
            get {
                return ResourceManager.GetStream("Click_6", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Click_7 {
            get {
                return ResourceManager.GetStream("Click_7", resourceCulture);
            }
        }
    }
}
